language: php

php:
  - 5.6
  - 7.0

env:
  - TRAVIS_NODE_VERSION="6"

services:
  - mysql
  - redis-server

before_install:
  - "npm config set spin false"

install:
  - cp .env.travis .env
  - composer self-update
  - npm install -g yarn gulp
  - mysql -u root -e 'create database `irispass-admin-testing`;'

before_script:
  - yarn
  - gulp
  - composer install  --prefer-dist --no-interaction --dev

script:
  - vendor/bin/codecept run

notifications:
    slack: 'n64:rMScyWuafH7BrnxKjSiPCfQM#irispass'
