language: php

php:
  - 5.6
  - 7.0

services:
  - mysql
  - redis-server

install:
  - cp .env.travis .env.testing
  - cp .env.travis .env
  - composer self-update
  - nvm install node
  - npm install -g yarn gulp
  - mysql -u root -e 'create database `irispass-admin-testing`;'

before_script:
  - yarn
  - gulp
  - composer install  --prefer-dist --no-interaction --dev

script:
  - vendor/bin/codecept run

notifications:
    slack: 'n64:rMScyWuafH7BrnxKjSiPCfQM#irispass'
