language: php

php:
  - 5.6
  - 7.0

services:
  - mysql
  - redis-server

before_install:
  - "npm config set spin false"

install:
  - cp .env.travis .env
  - composer self-update
  - npm install -g yarn gulp
  - yarn
  - gulp

before_script:
  - mysql -e 'create database irispass-admin-testing;'
  - composer install  --prefer-dist --no-interaction --dev

script:
  - vendor/bin/codecept run

notifications:
    slack: 'n64:rMScyWuafH7BrnxKjSiPCfQM#irispass'
